# Generated by Django 5.1.5 on 2025-02-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auditlog_delete_allticket_delete_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Client'), (4, 'Employee'), (5, 'User')], primary_key=True, serialize=False),
        ),
    ]
