# Generated by Django 5.1.5 on 2025-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
