# Generated by Django 5.1.5 on 2025-03-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_priority_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('view_staff_dashboard', 'Can view staff dashboard'), ('create_ticket', 'Can create ticket'), ('view_ticket', 'Can view ticket'), ('comment_ticket', 'Can comment on ticket'), ('close_ticket', 'Can close ticket'), ('view_org_tickets', 'Can view organization tickets')]},
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='department',
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Client'), (4, 'Employee'), (5, 'User'), (6, 'Staff')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.priority'),
        ),
    ]
