# Generated by Django 5.1.5 on 2025-03-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_priority_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Closed'), (3, 'Pending')], default=1),
        ),
    ]
